language: python

cache:
    directories:
        - $HOME/.cache/pip

before_install:
  # In the test-everything branch, we merge master before running tests.
  # This is because we want test-everything to test the code in master nightly
  # in a Travis cron, but with a different set of tests than master has
  # in .travis.yml.
  - '([ $TRAVIS_OS_NAME == linux ] && dpkg -s libaugeas0) || (brew update && brew install augeas && brew upgrade python python3 && brew link python)'

before_script:
  - 'if [ $TRAVIS_OS_NAME = osx ] ; then ulimit -n 1024 ; fi'

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27-certbot-oldest BOULDER_INTEGRATION=v1 INTEGRATION=nginx
      sudo: required
      services: docker
    - python: "2.7"
      env: TOXENV=py27-certbot-oldest BOULDER_INTEGRATION=v2 INTEGRATION=nginx
      sudo: required
      services: docker
    - python: "2.7"
      env: TOXENV=py27-nginx-oldest BOULDER_INTEGRATION=v1 INTEGRATION=nginx
      sudo: required
      services: docker
    - python: "2.7"
      env: TOXENV=py27-nginx-oldest BOULDER_INTEGRATION=v2 INTEGRATION=nginx
      sudo: required
      services: docker


# Only build pushes to the master branch, PRs, and branches beginning with
# `test-` or of the form `digit(s).digit(s).x`. This reduces the number of
# simultaneous Travis runs, which speeds turnaround time on review since there
# is a cap of on the number of simultaneous runs.
branches:
  only:
    - master
    - /^\d+\.\d+\.x$/
    - /^test-.*$/

# container-based infrastructure
sudo: false

addons:
  apt:
    packages:  # Keep in sync with letsencrypt-auto-source/pieces/bootstrappers/deb_common.sh and Boulder.
    - python-dev
    - python-virtualenv
    - gcc
    - libaugeas0
    - libssl-dev
    - libffi-dev
    - ca-certificates
    # For certbot-nginx integration testing
    - nginx-light
    - openssl

install: "travis_retry $(command -v pip || command -v pip3) install codecov tox"
script:
    - travis_retry tox
    - '[ -z "${BOULDER_INTEGRATION+x}" ] || (travis_retry tests/boulder-fetch.sh && tests/tox-boulder-integration.sh)'

after_success: '[ "$TOXENV" == "cover" ] && codecov'

notifications:
  email: false
