language: python

cache:
    directories:
        - $HOME/.cache/pip

before_install:
  - 'if [ $TRAVIS_OS_NAME = osx ] ; then brew update && brew install augeas python3 && brew upgrade python && brew link python; fi'

before_script:
  - 'if [ $TRAVIS_OS_NAME = osx ] ; then ulimit -n 1024 ; fi'

matrix:
  include:
    - python: "3.7"
      dist: xenial
      env: TOXENV=py37
      sudo: required
      services: docker


# Only build pushes to the master branch, PRs, and branches beginning with
# `test-` or of the form `digit(s).digit(s).x`. This reduces the number of
# simultaneous Travis runs, which speeds turnaround time on review since there
# is a cap of on the number of simultaneous runs.
branches:
  only:
    - master
    - /^\d+\.\d+\.x$/
    - /^test-.*$/

# container-based infrastructure
sudo: false

addons:
  apt:
    packages:  # Keep in sync with letsencrypt-auto-source/pieces/bootstrappers/deb_common.sh and Boulder.
    - python-dev
    - python-virtualenv
    - gcc
    - libaugeas0
    - libssl-dev
    - libffi-dev
    - ca-certificates
    # For certbot-nginx integration testing
    - nginx-light
    - openssl

install: "travis_retry $(command -v pip || command -v pip3) install tox coveralls"
script:
    - travis_retry tox
    - '[ -z "${BOULDER_INTEGRATION+x}" ] || (travis_retry tests/boulder-fetch.sh && tests/tox-boulder-integration.sh)'

after_success: '[ "$TOXENV" == "cover" ] && coveralls'

notifications:
  email: false
