language: python

cache:
    directories:
        - $HOME/.cache/pip

before_install:
  - '([ $TRAVIS_OS_NAME == linux ] && dpkg -s libaugeas0) || (brew update && brew install augeas python3 && brew upgrade python && brew link python)'

before_script:
  - 'if [ $TRAVIS_OS_NAME = osx ] ; then ulimit -n 1024 ; fi'

matrix:
  include:
    - python: "2.7"
      env: BOULDER_INTEGRATION=v1 INTEGRATION_TEST=all TOXENV=py27_install
      sudo: required
      services: docker
    - python: "2.7"
      env: BOULDER_INTEGRATION=v2 INTEGRATION_TEST=all TOXENV=py27_install
      sudo: required
      services: docker
    - python: "2.7"
      env: TOXENV=py27-cover FYI="py27 tests + code coverage"
    - sudo: required
      env: TOXENV=nginx_compat
      services: docker
      before_install:
      addons:
    - python: "2.7"
      env: TOXENV=lint
    - python: "3.4"
      env: TOXENV=mypy
    - python: "3.5"
      env: TOXENV=mypy
    - python: "2.7"
      env: TOXENV='py27-{acme,apache,certbot,dns,nginx,postfix}-oldest'
      sudo: required
      services: docker
    - python: "3.4"
      env: TOXENV=py34
      sudo: required
      services: docker
    - python: "3.7"
      dist: xenial
      env: TOXENV=py37
      sudo: required
      services: docker
    - sudo: required
      env: TOXENV=apache_compat
      services: docker
      before_install:
      addons:
    - sudo: required
      env: TOXENV=le_auto_trusty
      services: docker
      before_install:
      addons:
    - python: "2.7"
      env:
        - BOULDER_FOR_TOX=1
        - TOXENV=apacheconftest
      sudo: required
    - python: "2.7"
      env: TOXENV=nginxroundtrip


# Only build pushes to the master branch, PRs, and branches beginning with
# `test-` or of the form `digit(s).digit(s).x`. This reduces the number of
# simultaneous Travis runs, which speeds turnaround time on review since there
# is a cap of on the number of simultaneous runs.
branches:
  only:
    - master
    - /^\d+\.\d+\.x$/
    - /^test-.*$/

# container-based infrastructure
sudo: false

addons:
  apt:
    packages:  # Keep in sync with letsencrypt-auto-source/pieces/bootstrappers/deb_common.sh and Boulder.
    - python-dev
    - python-virtualenv
    - gcc
    - libaugeas0
    - libssl-dev
    - libffi-dev
    - ca-certificates
    # For certbot-nginx integration testing
    - nginx-light
    - openssl

install: "travis_retry $(command -v pip || command -v pip3) install codecov tox"
script:
    - '[ -z "${BOULDER_FOR_TOX+x}" ] || travis_retry tests/boulder-fetch.sh'
    - travis_retry tox
    # If BOULDER_INTEGRATION is set, run integration tests. If BOULDER_FOR_TOX isn't set, we still need to start boulder.
    - '[ -z "${BOULDER_INTEGRATION+x}" ] || ( ( [ -n "${BOULDER_FOR_TOX+x}" ] || travis_retry tests/boulder-fetch.sh ) && tests/tox-boulder-integration.sh)'

after_success: '[ "$TOXENV" == "py27-cover" ] && codecov'

notifications:
  email: false
