jobs:
  - job: installer_run
    strategy:
      matrix:
        win2019:
          imageName: windows-2019
        win2016:
          imageName: vs2017-win2016
        win2012r2:
          imageName: vs2015-win2012r2
    pool:
      vmImage: $(imageName)
    steps:
      - script: powershell --version
